#!/usr/bin/env python
from stocktracker import stocktracker
import logging
logging.basicConfig(level=logging.ERROR, format="%(levelname)s %(asctime)s %(funcName)s %(lineno)d %(message)s")

stocktracker.start()
